# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 451c0513bdcf6ae0f6705bf763c10916822d74fdf3cb2b81dc8ab83ac45cd491433f75e4b44d46abb4882d288e9a56c723c047fe5cf5696c98bafd5b5f980e00

test:
  secret_key_base: 970fb1943dd1238459b58ba20c43f59965b8975547e32c44c4027ef763347350f49ba7b74dd4cce2d819bbd8e271c1dfd6ed97338433f0c8403faef2df68f142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
